# Generated by Django 6.0.2 on 2026-03-02 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_recipe_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="image",
        ),
    ]
