# Generated by Django 6.0.2 on 2026-03-02 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_remove_recipe_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="instrucions",
            new_name="instructions",
        ),
    ]
