# Generated by Django 5.2.8 on 2026-03-03 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0005_remove_recipe_ingredients_alter_ingredient_id_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Ingredient",
        ),
    ]
